# Generated by Django 2.1.7 on 2019-03-15 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContratRegister', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contrat_Test',
        ),
    ]
