# Generated by Django 2.1.7 on 2019-03-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContratRegister', '0002_delete_contrat_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='password',
        ),
    ]
