# Generated by Django 2.1.7 on 2019-03-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContratRegister', '0003_auto_20190316_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=200, null=True, unique=True),
        ),
    ]
