# Generated by Django 2.1.7 on 2019-03-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContratRegister', '0007_contrat_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='type_pack',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
