# Generated by Django 2.1.7 on 2019-03-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContratRegister', '0008_contrat_type_pack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrat',
            old_name='duree',
            new_name='date_fin_contrat',
        ),
    ]
