# Generated by Django 2.1.7 on 2019-03-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContratRegister', '0009_auto_20190316_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='date_debut_contrat',
            field=models.DateTimeField(default=None),
        ),
    ]
